/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.BloodTesterRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LocalHospitalAgencyEnterprise;
import Business.Network.Network;
import Business.Organization.DiseaseAnalysisOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BloodTestWorkRequest;
import Business.WorkQueue.DoctorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sahithi
 */
public class BloodTestWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    BloodTestWorkRequest request;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public BloodTestWorkRequestJPanel(JPanel userProcessContainer, BloodTestWorkRequest request, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        this.business = business;
        populateTable();
    }

       /**
     * Populates table
     */
    public void populateTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblHomelessPersonRecords1.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblHomelessPersonRecords2.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        if (request.getHomelessPerson() != null) {
            Object[] row = new Object[8];
            row[0] = request.getHomelessPerson().getName();
            row[1] = request.getHomelessPerson().getDob();
            row[2] = request.getHomelessPerson().getCity();
            row[3] = request.getHomelessPerson().getCurrentAddress();
            row[4] = request.getHomelessPerson().getSSNNo();
            row[5] = request.getHomelessPerson().getContactNo();
            row[6] = request.getHomelessPerson().getEmailAddress();
            row[7] = request.getHomelessPerson().getDependents();
            model1.addRow(row);
            Object[] rowSecond = new Object[7];
            rowSecond[0] = request.getHomelessPerson().getGender();
            rowSecond[1] = request.getHomelessPerson().isHasCriminalRecord() ? "Yes" : "No";
            rowSecond[2] = request.getHomelessPerson().isMajorIllness() ? "Yes" : "No";
            rowSecond[3] = request.getHomelessPerson().isCarrierDisease() ? "Yes" : "No";
            rowSecond[4] = request.getHomelessPerson().isGeneticDisease() ? "Yes" : "No";
            rowSecond[5] = request.gethospitalAllocationWorkRequest().getSymptoms();
            model2.addRow(rowSecond);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHomelessPersonRecords1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHomelessPersonRecords2 = new javax.swing.JTable();
        btnPassCheck = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHomelessPersonRecords3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHomelessPersonRecords4 = new javax.swing.JTable();
        btnPassCheck1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InterferonGammaLevelTextBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        WBCTextBox = new javax.swing.JTextField();
        NeutrophilisTextBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        HydroxTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BloodPressureTextBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DiabetesTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 111, 97));

        jPanel1.setBackground(new java.awt.Color(255, 111, 97));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHomelessPersonRecords1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        tblHomelessPersonRecords1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "DOB", "City", "current address", "SSNNo", "Contact No", "Email Address", "Dependents"
            }
        ));
        jScrollPane1.setViewportView(tblHomelessPersonRecords1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, 1155, 103));

        tblHomelessPersonRecords2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        tblHomelessPersonRecords2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gender", "Criminal Record", "Major Illness", "Carrier Illness", "Genetic Illness", "Symptoms"
            }
        ));
        jScrollPane2.setViewportView(tblHomelessPersonRecords2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 300, 1155, 105));

        btnPassCheck.setBackground(new java.awt.Color(181, 189, 137));
        btnPassCheck.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        btnPassCheck.setText("Send test results to Doctor");
        btnPassCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassCheckActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 360, 50));

        jPanel2.setBackground(new java.awt.Color(255, 111, 97));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHomelessPersonRecords3.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tblHomelessPersonRecords3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "DOB", "City", "current address", "SSNNo", "Contact No", "Email Address", "Dependents"
            }
        ));
        jScrollPane3.setViewportView(tblHomelessPersonRecords3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, 1155, 103));

        tblHomelessPersonRecords4.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tblHomelessPersonRecords4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Symptoms", "Gender", "Criminal Record?", "Major Illness??", "Carrier Illness??", "Genetic Illness??", "Symptoms"
            }
        ));
        jScrollPane4.setViewportView(tblHomelessPersonRecords4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 300, 1155, 105));

        btnPassCheck1.setBackground(new java.awt.Color(104, 144, 146));
        btnPassCheck1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        btnPassCheck1.setText("Mark Covid -");
        btnPassCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassCheck1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPassCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 250, 50));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 144, 146));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1155, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Person Details:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 143, 1155, 34));

        InterferonGammaLevelTextBox.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        InterferonGammaLevelTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterferonGammaLevelTextBoxActionPerformed(evt);
            }
        });
        jPanel2.add(InterferonGammaLevelTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 130, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel9.setText("Interferon gamma level(in IU/ml)");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel10.setText("WBC");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        WBCTextBox.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        WBCTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WBCTextBoxActionPerformed(evt);
            }
        });
        jPanel2.add(WBCTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 130, 30));

        NeutrophilisTextBox.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        NeutrophilisTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeutrophilisTextBoxActionPerformed(evt);
            }
        });
        jPanel2.add(NeutrophilisTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 130, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel11.setText("Neutrophilis(in %)");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        HydroxTextBox.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        HydroxTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HydroxTextBoxActionPerformed(evt);
            }
        });
        jPanel2.add(HydroxTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 130, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel8.setText("25 Hydrox Vit D (in ng/mL)");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel12.setText("Blood Pressure (in mm/Hg)");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        BloodPressureTextBox.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        BloodPressureTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPressureTextBoxActionPerformed(evt);
            }
        });
        jPanel2.add(BloodPressureTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 130, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel7.setText("FPG Diabetes Test(in mg/dL)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        DiabetesTextBox.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        DiabetesTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiabetesTextBoxActionPerformed(evt);
            }
        });
        jPanel2.add(DiabetesTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 130, 30));

        jLabel1.setBackground(new java.awt.Color(181, 189, 137));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOOD TEST DETAILS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1155, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1155, 34));

        backJButton.setBackground(new java.awt.Color(181, 189, 137));
        backJButton.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        backJButton.setText("<<");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BloodTestWorkAreaJPanel dwjp = (BloodTestWorkAreaJPanel) component;
        dwjp.populateReceiveTable();
        dwjp.populateSentTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnPassCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassCheckActionPerformed
        if (request.getStatus().equals("Completed")) {
            JOptionPane.showMessageDialog(null, "This request has already been completed by you!");
            return;
        }
        request.setStatus("Completed");
        request.setTestResult("Sent to Doctor");
        UserAccount account = new UserAccount();
        account.setUsername("None");
        request.gethospitalAllocationWorkRequest().setReceiver(account);
        request.gethospitalAllocationWorkRequest().setTestResult("Completed by Blood Tester and and sent to Disease Analyzer");
        DoctorWorkRequest fcRequest = new DoctorWorkRequest();
        fcRequest.setMessage("Disease Analysis");
        fcRequest.setSender(userAccount);
        fcRequest.setStatus("Sent");
        fcRequest.setHomelessPerson(request.getHomelessPerson());
        
        request.getHomelessPerson().setInterferonGammaLevel(InterferonGammaLevelTextBox.getText());
        request.getHomelessPerson().setWBC(WBCTextBox.getText());
        request.getHomelessPerson().setNeutrophilis(NeutrophilisTextBox.getText());
        request.getHomelessPerson().setHydrox(HydroxTextBox.getText());
        request.getHomelessPerson().setBloodPressure(BloodPressureTextBox.getText());
        request.getHomelessPerson().setDiabetes(DiabetesTextBox.getText());


        
        
        fcRequest.sethospitalAllocationWorkRequest(request.gethospitalAllocationWorkRequest());
        Date d = new Date();
        fcRequest.setRequestDate(d);
        Organization org = null;

        for (Network network : business.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof LocalHospitalAgencyEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof DiseaseAnalysisOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(fcRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(fcRequest);
            JOptionPane.showMessageDialog(this, "Request Sent to Disease Analysis Organization");
        }
    }//GEN-LAST:event_btnPassCheckActionPerformed

    private void DiabetesTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiabetesTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiabetesTextBoxActionPerformed

    private void HydroxTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HydroxTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HydroxTextBoxActionPerformed

    private void btnPassCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassCheck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPassCheck1ActionPerformed

    private void InterferonGammaLevelTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterferonGammaLevelTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InterferonGammaLevelTextBoxActionPerformed

    private void WBCTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WBCTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WBCTextBoxActionPerformed

    private void NeutrophilisTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeutrophilisTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NeutrophilisTextBoxActionPerformed

    private void BloodPressureTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPressureTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPressureTextBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodPressureTextBox;
    private javax.swing.JTextField DiabetesTextBox;
    private javax.swing.JTextField HydroxTextBox;
    private javax.swing.JTextField InterferonGammaLevelTextBox;
    private javax.swing.JTextField NeutrophilisTextBox;
    private javax.swing.JTextField WBCTextBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnPassCheck;
    private javax.swing.JButton btnPassCheck1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblHomelessPersonRecords1;
    private javax.swing.JTable tblHomelessPersonRecords2;
    private javax.swing.JTable tblHomelessPersonRecords3;
    private javax.swing.JTable tblHomelessPersonRecords4;
    // End of variables declaration//GEN-END:variables
}
